# permissions for end users to view multusnotifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: multusnotifier-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multus-notifier-operator
    app.kubernetes.io/part-of: multus-notifier-operator
    app.kubernetes.io/managed-by: kustomize
  name: multusnotifier-viewer-role
rules:
- apiGroups:
  - apps.f-i.de
  resources:
  - multusnotifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.f-i.de
  resources:
  - multusnotifiers/status
  verbs:
  - get
