---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.f-i.de
  resources:
  - multusnotifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.f-i.de
  resources:
  - multusnotifiers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.f-i.de
  resources:
  - multusnotifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.f-i.de
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
